### ISSUE TITLE
Add an approval action for the bot prs 

### ISSUE THREAD

**Issue by msclock** [serious-scaffold/ss-cpp#295]
See https://github.com/hmarr/auto-approve-action

**Comment by huxuan** [comment]
So what is the auto approve for? If it is mostly for renovate, seems renovate already support [automerge](https://docs.renovatebot.com/key-concepts/automerge/), but I have not tried it yet.

**Comment by msclock** [comment]
> what is the auto approve for

@huxuan I just notice there still requires a manual approval for main/master branches of **having protected approval rules** when I enabled the automerge on GitHub.🫤 And the official renovate has two bots to handle it here https://github.com/apps/renovate-approve-2 and https://github.com/apps/renovate-approve.

**Comment by huxuan** [comment]
> @huxuan Renovate suggests 2 [ways](https://docs.renovatebot.com/key-concepts/automerge/#required-pull-request-reviews): GitHub bypassing for specific users or approving bots. I'll try the bypassing way.

Great, just feel free to tell me if there is any convenient solution.
